version: "3"

tasks:
  generate:
    aliases:
      - gen
    desk: "Generate k8s config file"
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative